/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GoalItem = IDL.Record({
  'goal' : IDL.Text,
  'completed' : IDL.Bool,
});
export const GirlHero = IDL.Record({
  'votes' : IDL.Nat,
  'heroName' : IDL.Text,
});
export const JournalEntry = IDL.Record({
  'date' : IDL.Text,
  'mood' : IDL.Opt(IDL.Text),
  'text' : IDL.Text,
});
export const MadLib = IDL.Record({
  'storyTitle' : IDL.Text,
  'filledText' : IDL.Text,
});
export const PostIt = IDL.Record({ 'note' : IDL.Text, 'color' : IDL.Text });
export const ScavengerItem = IDL.Record({
  'found' : IDL.Bool,
  'itemName' : IDL.Text,
});
export const WallOfFameEntry = IDL.Record({
  'girlName' : IDL.Text,
  'reason' : IDL.Text,
});
export const BookPick = IDL.Record({
  'review' : IDL.Text,
  'title' : IDL.Text,
  'author' : IDL.Text,
  'rating' : IDL.Nat,
});
export const TriviaScore = IDL.Record({
  'username' : IDL.Text,
  'score' : IDL.Nat,
  'category' : IDL.Text,
});
export const VisionItem = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBookPick' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'addGoal' : IDL.Func([IDL.Text], [], []),
  'addJournalEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'addMadLib' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addPostIt' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addScavengerItem' : IDL.Func([IDL.Text], [], []),
  'addTriviaScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'addVisionItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addWallOfFameEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'completeGoal' : IDL.Func([IDL.Nat], [], []),
  'getAllGoals' : IDL.Func([], [IDL.Vec(GoalItem)], ['query']),
  'getAllHeroes' : IDL.Func([], [IDL.Vec(GirlHero)], ['query']),
  'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getAllMadLibs' : IDL.Func([], [IDL.Vec(MadLib)], ['query']),
  'getAllPostIts' : IDL.Func([], [IDL.Vec(PostIt)], ['query']),
  'getAllScavengerItems' : IDL.Func([], [IDL.Vec(ScavengerItem)], ['query']),
  'getAllWallOfFameEntries' : IDL.Func(
      [],
      [IDL.Vec(WallOfFameEntry)],
      ['query'],
    ),
  'getBookPicks' : IDL.Func([], [IDL.Vec(BookPick)], ['query']),
  'getTriviaScores' : IDL.Func([], [IDL.Vec(TriviaScore)], ['query']),
  'getVisionBoard' : IDL.Func([], [IDL.Vec(VisionItem)], ['query']),
  'markItemFound' : IDL.Func([IDL.Nat], [], []),
  'voteForHero' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GoalItem = IDL.Record({ 'goal' : IDL.Text, 'completed' : IDL.Bool });
  const GirlHero = IDL.Record({ 'votes' : IDL.Nat, 'heroName' : IDL.Text });
  const JournalEntry = IDL.Record({
    'date' : IDL.Text,
    'mood' : IDL.Opt(IDL.Text),
    'text' : IDL.Text,
  });
  const MadLib = IDL.Record({
    'storyTitle' : IDL.Text,
    'filledText' : IDL.Text,
  });
  const PostIt = IDL.Record({ 'note' : IDL.Text, 'color' : IDL.Text });
  const ScavengerItem = IDL.Record({
    'found' : IDL.Bool,
    'itemName' : IDL.Text,
  });
  const WallOfFameEntry = IDL.Record({
    'girlName' : IDL.Text,
    'reason' : IDL.Text,
  });
  const BookPick = IDL.Record({
    'review' : IDL.Text,
    'title' : IDL.Text,
    'author' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const TriviaScore = IDL.Record({
    'username' : IDL.Text,
    'score' : IDL.Nat,
    'category' : IDL.Text,
  });
  const VisionItem = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addBookPick' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
    'addGoal' : IDL.Func([IDL.Text], [], []),
    'addJournalEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'addMadLib' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addPostIt' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addScavengerItem' : IDL.Func([IDL.Text], [], []),
    'addTriviaScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'addVisionItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addWallOfFameEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'completeGoal' : IDL.Func([IDL.Nat], [], []),
    'getAllGoals' : IDL.Func([], [IDL.Vec(GoalItem)], ['query']),
    'getAllHeroes' : IDL.Func([], [IDL.Vec(GirlHero)], ['query']),
    'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getAllMadLibs' : IDL.Func([], [IDL.Vec(MadLib)], ['query']),
    'getAllPostIts' : IDL.Func([], [IDL.Vec(PostIt)], ['query']),
    'getAllScavengerItems' : IDL.Func([], [IDL.Vec(ScavengerItem)], ['query']),
    'getAllWallOfFameEntries' : IDL.Func(
        [],
        [IDL.Vec(WallOfFameEntry)],
        ['query'],
      ),
    'getBookPicks' : IDL.Func([], [IDL.Vec(BookPick)], ['query']),
    'getTriviaScores' : IDL.Func([], [IDL.Vec(TriviaScore)], ['query']),
    'getVisionBoard' : IDL.Func([], [IDL.Vec(VisionItem)], ['query']),
    'markItemFound' : IDL.Func([IDL.Nat], [], []),
    'voteForHero' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };