/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookPick {
  'review' : string,
  'title' : string,
  'author' : string,
  'rating' : bigint,
}
export interface GirlHero { 'votes' : bigint, 'heroName' : string }
export interface GoalItem { 'goal' : string, 'completed' : boolean }
export interface JournalEntry {
  'date' : string,
  'mood' : [] | [string],
  'text' : string,
}
export interface MadLib { 'storyTitle' : string, 'filledText' : string }
export interface PostIt { 'note' : string, 'color' : string }
export interface ScavengerItem { 'found' : boolean, 'itemName' : string }
export interface TriviaScore {
  'username' : string,
  'score' : bigint,
  'category' : string,
}
export interface VisionItem {
  'title' : string,
  'description' : string,
  'category' : string,
}
export interface WallOfFameEntry { 'girlName' : string, 'reason' : string }
export interface _SERVICE {
  'addBookPick' : ActorMethod<[string, string, string, bigint], undefined>,
  'addGoal' : ActorMethod<[string], undefined>,
  'addJournalEntry' : ActorMethod<[string, string, [] | [string]], undefined>,
  'addMadLib' : ActorMethod<[string, string], undefined>,
  'addPostIt' : ActorMethod<[string, string], undefined>,
  'addScavengerItem' : ActorMethod<[string], undefined>,
  'addTriviaScore' : ActorMethod<[string, bigint, string], undefined>,
  'addVisionItem' : ActorMethod<[string, string, string], undefined>,
  'addWallOfFameEntry' : ActorMethod<[string, string], undefined>,
  'completeGoal' : ActorMethod<[bigint], undefined>,
  'getAllGoals' : ActorMethod<[], Array<GoalItem>>,
  'getAllHeroes' : ActorMethod<[], Array<GirlHero>>,
  'getAllJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getAllMadLibs' : ActorMethod<[], Array<MadLib>>,
  'getAllPostIts' : ActorMethod<[], Array<PostIt>>,
  'getAllScavengerItems' : ActorMethod<[], Array<ScavengerItem>>,
  'getAllWallOfFameEntries' : ActorMethod<[], Array<WallOfFameEntry>>,
  'getBookPicks' : ActorMethod<[], Array<BookPick>>,
  'getTriviaScores' : ActorMethod<[], Array<TriviaScore>>,
  'getVisionBoard' : ActorMethod<[], Array<VisionItem>>,
  'markItemFound' : ActorMethod<[bigint], undefined>,
  'voteForHero' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];