/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PostIt {
    note: string;
    color: string;
}
export interface GirlHero {
    votes: bigint;
    heroName: string;
}
export interface GoalItem {
    goal: string;
    completed: boolean;
}
export interface JournalEntry {
    date: string;
    mood?: string;
    text: string;
}
export interface TriviaScore {
    username: string;
    score: bigint;
    category: string;
}
export interface MadLib {
    storyTitle: string;
    filledText: string;
}
export interface WallOfFameEntry {
    girlName: string;
    reason: string;
}
export interface ScavengerItem {
    found: boolean;
    itemName: string;
}
export interface VisionItem {
    title: string;
    description: string;
    category: string;
}
export interface BookPick {
    review: string;
    title: string;
    author: string;
    rating: bigint;
}
export interface backendInterface {
    addBookPick(title: string, author: string, review: string, rating: bigint): Promise<void>;
    addGoal(goal: string): Promise<void>;
    addJournalEntry(text: string, date: string, mood: string | null): Promise<void>;
    addMadLib(storyTitle: string, filledText: string): Promise<void>;
    addPostIt(note: string, color: string): Promise<void>;
    addScavengerItem(itemName: string): Promise<void>;
    addTriviaScore(username: string, score: bigint, category: string): Promise<void>;
    addVisionItem(title: string, description: string, category: string): Promise<void>;
    addWallOfFameEntry(girlName: string, reason: string): Promise<void>;
    completeGoal(id: bigint): Promise<void>;
    getAllGoals(): Promise<Array<GoalItem>>;
    getAllHeroes(): Promise<Array<GirlHero>>;
    getAllJournalEntries(): Promise<Array<JournalEntry>>;
    getAllMadLibs(): Promise<Array<MadLib>>;
    getAllPostIts(): Promise<Array<PostIt>>;
    getAllScavengerItems(): Promise<Array<ScavengerItem>>;
    getAllWallOfFameEntries(): Promise<Array<WallOfFameEntry>>;
    getBookPicks(): Promise<Array<BookPick>>;
    getTriviaScores(): Promise<Array<TriviaScore>>;
    getVisionBoard(): Promise<Array<VisionItem>>;
    markItemFound(id: bigint): Promise<void>;
    voteForHero(heroName: string): Promise<void>;
}
import type { JournalEntry as _JournalEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBookPick(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBookPick(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBookPick(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addGoal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGoal(arg0);
            return result;
        }
    }
    async addJournalEntry(arg0: string, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addJournalEntry(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJournalEntry(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addMadLib(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMadLib(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMadLib(arg0, arg1);
            return result;
        }
    }
    async addPostIt(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPostIt(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPostIt(arg0, arg1);
            return result;
        }
    }
    async addScavengerItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addScavengerItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScavengerItem(arg0);
            return result;
        }
    }
    async addTriviaScore(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTriviaScore(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTriviaScore(arg0, arg1, arg2);
            return result;
        }
    }
    async addVisionItem(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVisionItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVisionItem(arg0, arg1, arg2);
            return result;
        }
    }
    async addWallOfFameEntry(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWallOfFameEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWallOfFameEntry(arg0, arg1);
            return result;
        }
    }
    async completeGoal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeGoal(arg0);
            return result;
        }
    }
    async getAllGoals(): Promise<Array<GoalItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGoals();
            return result;
        }
    }
    async getAllHeroes(): Promise<Array<GirlHero>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHeroes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHeroes();
            return result;
        }
    }
    async getAllJournalEntries(): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJournalEntries();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJournalEntries();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMadLibs(): Promise<Array<MadLib>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMadLibs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMadLibs();
            return result;
        }
    }
    async getAllPostIts(): Promise<Array<PostIt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPostIts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPostIts();
            return result;
        }
    }
    async getAllScavengerItems(): Promise<Array<ScavengerItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllScavengerItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllScavengerItems();
            return result;
        }
    }
    async getAllWallOfFameEntries(): Promise<Array<WallOfFameEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWallOfFameEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWallOfFameEntries();
            return result;
        }
    }
    async getBookPicks(): Promise<Array<BookPick>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookPicks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookPicks();
            return result;
        }
    }
    async getTriviaScores(): Promise<Array<TriviaScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTriviaScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTriviaScores();
            return result;
        }
    }
    async getVisionBoard(): Promise<Array<VisionItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisionBoard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisionBoard();
            return result;
        }
    }
    async markItemFound(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markItemFound(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markItemFound(arg0);
            return result;
        }
    }
    async voteForHero(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.voteForHero(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voteForHero(arg0);
            return result;
        }
    }
}
function from_candid_JournalEntry_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JournalEntry): JournalEntry {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    mood: [] | [string];
    text: string;
}): {
    date: string;
    mood?: string;
    text: string;
} {
    return {
        date: value.date,
        mood: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.mood)),
        text: value.text
    };
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JournalEntry>): Array<JournalEntry> {
    return value.map((x)=>from_candid_JournalEntry_n3(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
